#!/usr/bin/env bash

# fail fast
set -e

APP_VOLUME=${IMAGE_APP_VOLUME:-/app}

home_mounts=".aws .terraform.d .atmos.yml"
mounts=""
for mount in $home_mounts; do
  if [[ -e $HOME/$mount ]]; then
    mounts="$mounts --mount type=bind,source=$HOME/$mount,target=/root/$mount"
  fi
done

docker run \
  --interactive --tty --rm \
  --volume "$(pwd)":"${APP_VOLUME}" \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  $mounts \
  --env-file <(env | grep "^AWS\|^ATMOS\|^TF") \
  simplygenius/atmos "$@"
